name: Build site
on:
 push:
   branches:
   - master
#  schedule:
#  - cron: '23 12,16,18,20,22 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r requirements.txt
    # looks like older Shapely does not build, newer as used by nix
    # not compatible with pyopenair's metadata, but seems to work
    - run: pip install --no-deps pyopenair==1.1.0
    - run: ./prepare.sh
      env:
        DHV_USERNAME: ${{ secrets.DHV_USERNAME }}
        DHV_PASSWORD: ${{ secrets.DHV_PASSWORD }}
    - run: ./fetch-flights.sh
    - name: Fetch igc cache
      uses: actions/cache@v4
      with:
        key:  flights-1-${{hashFiles('_tmp/flights.json')}}
        restore-keys:  flights-1-
        path: _flights
    - run: ./fetch-igc.sh
    - name: Upload igc cache
      uses: actions/cache/save@v4
      if: always()
      with:
        key:  flights-1-${{hashFiles('_tmp/flights.json')}}
        path: _flights
    - name: Fetch stats cache
      uses: actions/cache@v4
      with:
        key:  stats-${{hashFiles('*.py')}}-${{hashFiles('_tmp/flights.json')}}
        restore-keys:  stats-${{hashFiles('*.py')}}-
        path: _stats
    - run: ./update-flightstats.py
    - name: Upload stats cache
      uses: actions/cache/save@v4
      if: always()
      with:
        key:  stats-${{hashFiles('*.py')}}-${{hashFiles('_tmp/flights.json')}}
        path: _stats

    - run: ./sektoren-map.py
    - run: ./website.py

    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_out'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
